LENGUAJES = [
  {
        id: "python",
        nombre: "Python",
        year: "1991",
        author: "Guido van Rossum",
        queEs: "Un lenguaje de programación de alto nivel, conocido por su sintaxis clara y legible, que enfatiza la productividad del desarrollador.",
        tipo: "Alto Nivel, Interpretado",
        caracteristicas: "Sintaxis simple y elegante, una vasta biblioteca estándar y un fuerte ecosistema para ciencia de datos y machine learning.",
        uso: "Web (Backend), Ciencia de Datos, Automatización, ML.",
        historia: "Creado por Guido van Rossum y lanzado en 1991. Su nombre se inspira en el grupo de comedia británico 'Monty Python'.",
        beneficios: "Curva de aprendizaje suave, gran comunidad y una enorme cantidad de librerías que aceleran el desarrollo.",
        comoSeUtiliza: "Se utiliza para crear servidores web con frameworks como Django o Flask, analizar datos con Pandas, entrenar modelos de inteligencia artificial con TensorFlow y automatizar tareas repetitivas.",
        datosInteresantes: "El 'Zen de Python' es un conjunto de 19 principios que guían su diseño, como 'Bello es mejor que feo' y 'Simple es mejor que complejo'.",
        codigo: 'print("Hola mundo, Python")',
        color: "#306998",
        imagen: "https://e7.pngegg.com/pngimages/761/45/png-clipart-professional-python-programmer-computer-programming-android-android-blue-logo-thumbnail.png"
    },
    {

        id: "javascript",
        year: "1995",
        author: "Brendan Eich",
        nombre: "JavaScript (JS)",
        queEs: "El lenguaje de programación que impulsa la web interactiva. Es fundamental para el desarrollo frontend y también popular en el backend.",
        tipo: "Alto Nivel, Interpretado/JIT Compilado",
        caracteristicas: "Funciona en el navegador del cliente, es asíncrono por naturaleza y tiene un ecosistema masivo a través de Node.js y npm.",
        uso: "Web (Frontend), Web (Backend), Móvil (React Native).",
        historia: "Creado por Brendan Eich en Netscape en solo 10 días en 1995. Originalmente se llamaba 'Mocha' y luego 'LiveScript'.",
        beneficios: "Es el único lenguaje que se ejecuta de forma nativa en los navegadores, lo que lo hace indispensable para el desarrollo web. Permite crear aplicaciones full-stack.",
        comoSeUtiliza: "Se usa para crear efectos visuales, validar formularios, comunicarse con servidores (AJAX/Fetch) y construir complejas aplicaciones de una sola página (SPA) con frameworks como React, Angular o Vue.",
        datosInteresantes: "A pesar de su nombre, JavaScript no tiene una relación directa con Java. El nombre fue una decisión de marketing para aprovechar la popularidad de Java en ese momento.",
        codigo: 'function saludar() {\n  alert("Hola JavaScript!");\n}',
        color: "#F7DF1E",
        imagen: "https://thumbs.dreamstime.com/b/javascript-logo-editorial-ilustrativo-sobre-fondo-blanco-illustrative-white-background-eps-descargar-vector-jpeg-banner-208329455.jpg"
    },
    {
        id: "java",
        nombre: "Java",
        year: "1995",
        author: "James Gosling",
        queEs: "Un lenguaje de programación robusto, orientado a objetos y diseñado para ser portable, permitiendo que las aplicaciones se ejecuten en cualquier plataforma con una Máquina Virtual de Java (JVM).",
        tipo: "Alto Nivel, Compilado (a bytecode JVM)",
        caracteristicas: "Fuertemente tipado, orientado a objetos, y su lema es 'Escribe una vez, ejecuta en cualquier lugar' (WORA) gracias a la JVM.",
        uso: "Aplicaciones Empresariales (Enterprise), Android nativo, Big Data.",
        historia: "Desarrollado por James Gosling en Sun Microsystems y lanzado en 1995. Originalmente fue diseñado para la televisión interactiva.",
        beneficios: "Su portabilidad a través de la Máquina Virtual de Java (JVM) es su mayor ventaja. Es robusto, seguro y tiene un excelente rendimiento para aplicaciones a gran escala.",
        comoSeUtiliza: "Es la base de grandes sistemas bancarios, aplicaciones de Android (aunque ahora compite con Kotlin), y herramientas de Big Data como Hadoop.",
        datosInteresantes: "El nombre 'Java' proviene del café de Java (Indonesia), y es por eso que su logo es una taza de café humeante.",
        codigo: 'public class Saludo {\n  public static void main(String[] args) {\n    System.out.println("Hola Java!");\n  }\n}',
        color: "#5382a1",
        imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTzEtSfJsjoe-KaB3aCQ5PyHnZhVymW3QM2w&s"
    },
    {
        id: "c",
        nombre: "C",
        year: "1972",
        author: "Dennis Ritchie",
        queEs: "Considerado el 'padre' de muchos lenguajes modernos, C es un lenguaje de propósito general que ofrece un control casi total sobre el hardware del sistema.",
        tipo: "Bajo Nivel / Nivel Medio, Compilado",
        caracteristicas: "Rendimiento extremadamente alto, gestión manual de la memoria (punteros) y portabilidad a nivel de sistema.",
        uso: "Sistemas Operativos (Kernels), Sistemas Embebidos, Desarrollo de Hardware, Compiladores.",
        historia: "Creado por Dennis Ritchie en los Laboratorios Bell en 1972 para desarrollar el sistema operativo UNIX.",
        beneficios: "Ofrece un control sin precedentes sobre el hardware y la memoria, lo que resulta en programas extremadamente rápidos y eficientes.",
        comoSeUtiliza: "Se usa para escribir el núcleo (kernel) de sistemas operativos como Linux y Windows, para programar microcontroladores y para crear otros lenguajes de programación.",
        datosInteresantes: "El famoso libro 'The C Programming Language' de Kernighan y Ritchie (a menudo llamado 'K&R') fue durante décadas la especificación no oficial del lenguaje.",
        codigo: '#include <stdio.h>\nint main() {\n  printf("Hola C!\\n");\n  return 0;\n}',
        color: "#A8B9CC",
        imagen: "https://upload.wikimedia.org/wikipedia/commons/1/19/C_Logo.png"
    },
    {
        id: "cplusplus",
        nombre: "C++",
        year: "1983",
        author: "Bjarne Stroustrup",
        queEs: "Una extensión del lenguaje C que añade soporte para la programación orientada a objetos. Es conocido por su increíble rendimiento.",
        tipo: "Nivel Medio (cercano al hardware), Compilado",
        caracteristicas: "Combina paradigmas de programación procedural y orientada a objetos, ofrece gestión de memoria de bajo nivel y es extremadamente rápido.",
        uso: "Videojuegos (Motores Gráficos), Sistemas Operativos, Drivers.",
        historia: "Creado por Bjarne Stroustrup en 1983 como una extensión de C, añadiendo clases y características de la programación orientada a objetos.",
        beneficios: "Rendimiento excepcional, ideal para aplicaciones que requieren un uso intensivo de la CPU, como los motores de videojuegos (Unreal Engine) o software de cálculo científico.",
        comoSeUtiliza: "Es el lenguaje preferido para desarrollar videojuegos AAA, sistemas operativos, navegadores web (como Chrome y Firefox) y software de trading de alta frecuencia.",
        datosInteresantes: "El '++' en C++ es un guiño al operador de incremento en C, simbolizando que es una evolución o 'un paso más allá' de C.",
        codigo: '#include <iostream>\nint main() {\n  std::cout << "Hola C++" << std::endl;\n  return 0;\n}',
        color: "#00599c",
        imagen: "https://w7.pngwing.com/pngs/646/751/png-transparent-the-c-programming-language-computer-programming-programmer-others-blue-class-logo-thumbnail.png"
    },
    {
        id: "csharp",
        nombre: "C# (C-Sharp)",
        year: "2000",
        author: "Anders Hejlsberg",
        queEs: "Un lenguaje moderno y versátil desarrollado por Microsoft como parte de su plataforma .NET. Es ampliamente utilizado para crear aplicaciones de Windows, web y videojuegos.",
        tipo: "Alto Nivel, Compilado (a IL para la plataforma .NET)",
        caracteristicas: "Fuertemente tipado, orientado a componentes, y se integra perfectamente con el ecosistema de desarrollo de Microsoft (Visual Studio, .NET).",
        uso: "Videojuegos (Motor Unity), Web (Backend) con ASP.NET Core, Aplicaciones de Escritorio.",
        historia: "Desarrollado por Microsoft bajo la dirección de Anders Hejlsberg y lanzado en 2000 como parte de la iniciativa .NET.",
        beneficios: "Es un lenguaje moderno con características potentes, una sintaxis limpia y un fuerte respaldo de Microsoft, lo que lo hace ideal para el desarrollo empresarial.",
        comoSeUtiliza: "Es el lenguaje principal para el motor de videojuegos Unity. También se usa para crear servicios web con ASP.NET y aplicaciones de escritorio para Windows.",
        datosInteresantes: "El nombre 'C#' se inspiró en la notación musical, donde una nota 'sostenida' (sharp) es un semitono más alto, sugiriendo que C# es un incremento sobre C++.",
        codigo: 'public static void Main(string[] args) {\n  Console.WriteLine("Hola C#!");\n}',
        color: "#68217A",
        imagen: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Csharp_Logo.png"
    },
    {
        id: "swift",
        nombre: "Swift",
        year: "2014",
        author: "Apple",
        queEs: "El lenguaje de programación moderno, rápido y seguro creado por Apple para desarrollar aplicaciones en todo su ecosistema (iOS, macOS, etc.).",
        tipo: "Alto Nivel, Compilado",
        caracteristicas: "Sintaxis concisa y expresiva, seguridad contra errores comunes (manejo de nulos con opcionales) y un rendimiento comparable al de C++.",
        uso: "Aplicaciones Nativas para iOS, macOS, watchOS y tvOS.",
        historia: "Presentado por Apple en 2014 como un sucesor moderno y más seguro de Objective-C.",
        beneficios: "Está diseñado para ser seguro por defecto, evitando categorías enteras de errores de programación. Es rápido, moderno y fácil de leer.",
        comoSeUtiliza: "Es el lenguaje estándar para crear cualquier aplicación para iPhone, iPad, Mac, Apple Watch y Apple TV.",
        datosInteresantes: "Swift se hizo de código abierto en 2015, lo que permite a la comunidad usarlo también en el lado del servidor e incluso en otras plataformas.",
        codigo: 'let mensaje = "Hola Swift!"\nprint(mensaje)',
        color: "#FA7343",
        imagen: "https://e7.pngegg.com/pngimages/685/655/png-clipart-swift-essentials-programming-language-macos-c-apple-swift-programming-language.png"
    },
    {
        id: "ruby",
        nombre: "Ruby",
        year: "1995",
        author: "Yukihiro Matsumoto",
        queEs: "Un lenguaje dinámico y de código abierto con un enfoque en la simplicidad y la productividad. Su lema es 'El mejor amigo de un programador'.",
        tipo: "Alto Nivel, Interpretado",
        caracteristicas: "Sintaxis natural y fácil de leer, todo es un objeto, y promueve el principio de 'No te repitas' (DRY).",
        uso: "Desarrollo Web (Backend), automatización de scripts.",
        historia: "Creado por Yukihiro 'Matz' Matsumoto en Japón a mediados de la década de 1990. Quería un lenguaje que se centrara en la felicidad del programador.",
        beneficios: "Su sintaxis elegante permite escribir código de forma rápida y natural. El framework Ruby on Rails revolucionó el desarrollo web con su filosofía de 'convención sobre configuración'.",
        comoSeUtiliza: "Es famoso por el framework Ruby on Rails, usado para construir rápidamente aplicaciones web robustas como GitHub, Airbnb y Shopify.",
        datosInteresantes: "En Ruby, puedes escribir cosas como `5.times { print 'Hola' }`, lo que demuestra su enfoque en una sintaxis legible y cercana al lenguaje humano.",
        codigo: 'def saludar(nombre)\n  puts "Hola, \#{nombre}"\nend',
        color: "#CC342D",
        imagen: "https://www.ensalza.com/blog/wp-content/uploads/que-es-ruby.jpg"
    },
    {
        id: "php",
        nombre: "PHP",
        year: "1994",
        author: "Rasmus Lerdorf",
        queEs: "Un popular lenguaje de scripting del lado del servidor diseñado especialmente para el desarrollo web. Es el motor de una gran parte de los sitios web del mundo.",
        tipo: "Alto Nivel, Interpretado (procesado en el servidor)",
        caracteristicas: "Fácil de aprender, gran comunidad, amplia compatibilidad con bases de datos y es la base de sistemas como WordPress y Laravel.",
        uso: "Web (Backend), CMS como WordPress y frameworks como Laravel.",
        historia: "Creado por Rasmus Lerdorf en 1994 como un conjunto de scripts para rastrear las visitas a su currículum en línea. Originalmente significaba 'Personal Home Page'.",
        beneficios: "Es extremadamente fácil de desplegar en la mayoría de los servidores web. Su enorme comunidad significa que hay soluciones y tutoriales para casi cualquier problema.",
        comoSeUtiliza: "Es el lenguaje en el que está construido WordPress, el CMS más popular del mundo. También se usa con frameworks modernos como Laravel y Symfony para crear aplicaciones web complejas.",
        datosInteresantes: "Se estima que PHP se utiliza en más del 75% de todos los sitios web cuyo lenguaje del lado del servidor se conoce.",
        codigo: '<?php\n$nombre = "PHP";\necho "<h1>Hola \$nombre!</h1>";\n?>',
        color: "#777BB4",
        imagen: "https://upload.wikimedia.org/wikipedia/commons/2/27/PHP-logo.svg"
    },
    {
        id: "html",
        nombre: "HTML",
        year: "1991",
        author: "Tim Berners-Lee",
        queEs: "HyperText Markup Language (Lenguaje de Marcado de Hipertexto) es el esqueleto de todas las páginas web. No es un lenguaje de programación, sino de marcado.",
        tipo: "Lenguaje de Marcado",
        caracteristicas: "Utiliza etiquetas para estructurar el contenido, es el estándar para la creación de sitios web y es interpretado directamente por los navegadores.",
        uso: "Estructura de cualquier página Web o aplicación.",
        historia: "Sus orígenes se remontan a 1980, pero la primera descripción formal de HTML fue publicada por Tim Berners-Lee en 1991.",
        beneficios: "Es el estándar universal para la web, soportado por todos los navegadores. Es fácil de aprender y es la base fundamental de todo el desarrollo web.",
        comoSeUtiliza: "Se usa para definir todos los elementos de una página: títulos (`<h1>`), párrafos (`<p>`), imágenes (`<img>`), enlaces (`<a>`), formularios (`<form>`), etc.",
        datosInteresantes: "HTML5, la versión más reciente, introdujo etiquetas semánticas como `<article>`, `<section>` y `<nav>`, que ayudan a los motores de búsqueda a entender mejor la estructura del contenido.",
        codigo: '<h1>Título de la Sección</h1>\n<p>Contenido del artículo.</p>',
        color: "#E34C26",
        imagen: "https://thumbs.dreamstime.com/b/astana-kazajst%C3%A1n-de-julio-icono-html-logotipo-s%C3%ADmbolo-vector-198641993.jpg"
    },
    {
        id: "css",
        nombre: "CSS",
        year: "1994",
        author: "Håkon Wium Lie",
        queEs: "Cascading Style Sheets (Hojas de Estilo en Cascada) es el lenguaje utilizado para describir la presentación y el diseño de un documento escrito en HTML.",
        tipo: "Lenguaje de Hojas de Estilo",
        caracteristicas: "Separa el contenido (HTML) de la presentación, permite crear diseños complejos (Flexbox, Grid) y soporta animaciones y transiciones.",
        uso: "Estilos y Diseño de cualquier página Web o aplicación.",
        historia: "Propuesto por Håkon Wium Lie en 1994 y estandarizado por el W3C. Fue creado para separar la estructura del documento (HTML) de su presentación visual.",
        beneficios: "Permite mantener un diseño consistente en todo un sitio web modificando un solo archivo. Facilita la creación de diseños responsivos que se adaptan a diferentes tamaños de pantalla.",
        comoSeUtiliza: "Se escribe en archivos `.css` o directamente en etiquetas HTML para definir colores, fuentes, márgenes, posicionamiento y animaciones de los elementos.",
        datosInteresantes: "El nombre 'Hojas de Estilo en Cascada' se refiere a la forma en que se aplican las reglas: los estilos de una fuente más específica (en cascada) anulan a los de una fuente más general.",
        codigo: 'p {\n  color: #333;\n  font-size: 16px;\n}',
        color: "#264de4",
        imagen: "https://upload.wikimedia.org/wikipedia/commons/d/d5/CSS3_logo_and_wordmark.svg"
    }
];